# .gitleaks.toml - Updated for Gitleaks v8+
# Gitleaks documentation: https://gitleaks.io/docs/config/

# Allowlist section for excluding paths
[allowlist]

# Paths to ignore. Gitleaks will not scan files within these paths.
# Use standard Gitignore-like patterns.
paths = [
  '''node_modules/''' # Exclude the entire node_modules directory
]

# You can add other global allowlist options here if needed, e.g.:
# regexes = [ '(?i)some_safe_pattern' ] # Regex for patterns to ignore globally
# commits = [ 'a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0' ] # Commit SHAs to ignore
